# Porta
http_port 3128

# Rede local
acl rede_local src 192.168.10.0/24

# Sites bloqueados
acl sites_bloqueados dstdomain "/etc/squid/blocked-sites.txt"

# ORDEM CORRETA
http_access deny sites_bloqueados
http_access allow rede_local
http_access deny all

# Desativar IPv6 no Squid
dns_v4_first on 
