[global]
   workgroup = LAB
   server string = Servidor de Arquivos LAB
   security = user
   map to guest = bad user
   dns proxy = no
   log file = /var/log/samba/log.%m
   max log size = 1000

   # Lixeira
   vfs objects = recycle
   recycle:repository = /srv/samba/lixeira/%U
   recycle:keeptree = yes
   recycle:versions = yes

[publico]
   path = /srv/samba/publico
   guest ok = yes
   browseable = yes
   writable = yes

[ti]
   path = /srv/samba/ti
   valid users = joao maria
   browseable = yes
   writable = yes
   create mask = 0660
   directory mask = 0770

[financeiro]
   path = /srv/samba/financeiro
   valid users = maria
   read list = joao
   writable = yes
   browseable = no
   veto files = /*.exe/*.mp3/*.mp4/*.avi/
